### ISSUE TITLE
BUG: Point类中tag值的字符校验不允许加号(+)的问题

### ISSUE THREAD

**Issue by vancepym** [aliyun/HiTSDB-Client#10]
我在使用该SDK保存point时，其中有一个tag(arrive_time)值是ISO-8601格式时间字符串，但是报异常提示加号字符是非法的，我不明白为什么在 Point 类的 checkChar 方法中将加号字符排除掉了？是基于什么考虑需要排除加号字符？还是因为遗漏了该字符？

官方可否考虑允许加号(+)字符呢？

以下是异常提示内容：
java.lang.IllegalArgumentException: There is an invalid character in tagvalue. the tag is + <arrive_time:2018-08-04T21:01:16.000+08:00> , the char is '+'
	at com.aliyun.hitsdb.client.value.request.Point.checkPoint(Point.java:364)
	at com.aliyun.hitsdb.client.value.request.Point$MetricBuilder.build(Point.java:179)
	at com.aliyun.hitsdb.client.value.request.Point$MetricBuilder.build(Point.java:161)

**Comment by hujianhong** [comment]
这是出于支持正则表达式等模糊查询的角度考虑的，将一些特殊字符作为了保留字了，当前支持的特殊字符为：
![image](https://user-images.githubusercontent.com/20662146/51881451-31eac400-23b6-11e9-9092-def0a38bac32.png)
更多详情见：https://help.aliyun.com/document_detail/59939.html?spm=a2c4g.11174283.6.615.2f44130e8FyuIv
